### PR TITLE
 Support Harmony re-exports

### LINKED ISSUE #190: Compatibility issues with webpack 3.8.1
Re-opening #184 as my patch didn't seem to help 😞 

[Oleg is right](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/184#issuecomment-341056602) that webpack has changed to Sets and makes use of `.has` which could cause problems if hard-source is thawing arrays. I'm not entirely sure why `activeExports` would be null here though:

```
/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:60
				if(this.activeExports.has(id)) return false;
				                     ^

TypeError: Cannot read property 'has' of null
    at importedNames.originModule.usedExports.filter.id (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:60:26)
    at Array.filter (<anonymous>)
    at HardHarmonyExportImportedSpecifierDependency.getReference (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:58:56)
    at processDependency (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:52:48)
    at depBlock.dependencies.forEach.dep (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:43)
    at Array.forEach (<anonymous>)
    at processDependenciesBlock (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:28)
    at Compilation.compilation.plugin.modules (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:23:6)
    at Compilation.applyPluginsBailResult1 (/Users/rowanoulton/Projects/webapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:140:27)
    at Compilation.seal (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:597:9)
    at applyPluginsParallel.err (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compiler.js:508:17)
    at /Users/rowanoulton/Projects/webapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/rowanoulton/Projects/webapp/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Any theories?

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #190

### CODE REVIEW

**Comment by filipesilva** [comment]
@mzgoddard @rowanoulton @ohze I'm not 100% sure this solves all the re-export problems but on the examples I tried it seemed fine. PTAL.

**Comment by Kamilius** [comment]
Any news on when this pull request can be merged?

**Comment by mzgoddard** [comment]
@filipesilva @Kamilius Sorry for the delay. This looks great. Thanks!

**Comment by mzgoddard** [comment]
@filipesilva I'm happy enough to see progress made for re-export problems as we find them.

**Comment by zanettin** [comment]
@mzgoddard can you give us a note when you've published this fix and on which version?  thx a lot @filipesilva ❤️

**Comment by mzgoddard** [comment]
Published as `0.4.12` and `0.5.0-rc.4`

**Comment by mzgoddard** [comment]
@zanettin Yup. Had to backport the change a bit to get it in `0.4`.

**Comment by zanettin** [comment]
thx a lot @mzgoddard 

facing these issues running `0.4.12` and `0.5.0-rc.4`:

```
Starting the development server...

[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: /Users/myApp/node_modules/.cache/hard-source/fdc902b4c070f79b25e3fe2981d322915153030cd5d58a8bea493f96b1a91390

<--- Last few GCs --->

[14422:0x102802400]    43872 ms: Mark-sweep 1405.5 (1584.9) -> 1405.2 (1584.9) MB, 234.9 / 0.0 ms  allocation failure GC in old space requested
[14422:0x102802400]    44112 ms: Mark-sweep 1405.2 (1584.9) -> 1405.1 (1545.9) MB, 240.5 / 0.0 ms  last resort GC in old space requested
[14422:0x102802400]    44344 ms: Mark-sweep 1405.1 (1545.9) -> 1405.1 (1537.4) MB, 231.5 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3447d96a5e91 <JSObject>
    0: builtin exit frame: stringify(this=0x3447d9688ff1 <Object map = 0x344786e82ba1>,0x344774302311 <undefined>,0x344774302311 <undefined>,0x344761e7f5b9 <JSArray[2]>)

    1: arguments adaptor frame: 1->3
    2: /* anonymous */ [/Users/myApp/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:~86] [pc=0x35da07b9dc60](this=0x344733b3b649 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/Roman/.nvm/versions/node/v8.8.0/bin/node]
```

after allocating more memory `--max-old-space-size=4096`:

```
Starting the development server...

[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: /Users/myApp/node_modules/.cache/hard-source/fdc902b4c070f79b25e3fe2981d322915153030cd5d58a8bea493f96b1a91390
/Users/myAPp/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:99
      var _inContextDependencyIdentifier = module && JSON.stringify([module.context, frozen]);
                                                          ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Compiler.<anonymous> (/Users/myApp/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:99:59)
```

node: `8.8`
npm: `5.4.2`
webpack: `3.10.0`

any ideas? should I open a new issue? thx again

**Comment by mzgoddard** [comment]
@zanettin Yes please open a new issue.

**Comment by mzgoddard** [comment]
@zanettin I'll comment further on the new issue. If you can include any of the following info that'd be helpful:

- what loaders and plugins your project is using
- number of modules being built
- how big is the output js files normally?
- size of the output destination all together?

**Pull request merged**
